package com.example.debit.ui.utils

import com.example.debit.data.AppLanguage

object AppStrings {
    fun getCategoryName(category: String, language: AppLanguage): String {
        if (language == AppLanguage.ZH) return category
        return when (category) {
            "餐飲" -> "Dining"
            "日常" -> "Daily"
            "娛樂" -> "Entertainment"
            "購物" -> "Shopping"
            "交通" -> "Transport"
            "醫療" -> "Medical"
            "居住" -> "Housing"
            "其他" -> "Other"
            else -> category
        }
    }

    fun getSubCategoryName(sub: String, language: AppLanguage): String {
        if (language == AppLanguage.ZH) return sub
        return when (sub) {
            "早餐" -> "Breakfast"
            "午餐" -> "Lunch"
            "晚餐" -> "Dinner"
            "宵夜" -> "Late Snack"
            "點心飲料" -> "Snacks & Drinks"
            "洗衣" -> "Laundry"
            "烘衣" -> "Dryer"
            "電費" -> "Electricity"
            "日用品" -> "Household"
            else -> sub
        }
    }

    fun get(key: String, language: AppLanguage): String {
        return if (language == AppLanguage.ZH) getZhTw(key) else getEn(key)
    }

    private fun getZhTw(key: String): String = when (key) {
        "vault_overview" -> "小金庫概況"
        "spent_this_month" -> "本月已花費"
        "remaining_vault" -> "月度剩餘金庫"
        "vault_usage" -> "金庫用量"
        "target_budget" -> "月預算目標"
        "daily_subtotal" -> "當日開銷小計"
        "no_records_title" -> "今天尚未記帳呢"
        "no_records_subtitle" -> "要來記錄第一筆小開銷嗎？"
        "start_add" -> "開始第一筆記帳"
        "step_language" -> "選擇顯示語言"
        "step_theme" -> "選擇色彩主題"
        "step_budget" -> "設定月度預算"
        "settings" -> "偏好設定與工具"
        "set_budget" -> "規劃月度小金庫"
        "monthly_budget" -> "本月目標金庫 ($)"
        "theme_color" -> "色彩主題"
        "app_language" -> "語言偏好"
        "add_record" -> "記一筆"
        "add_expense" -> "新增一筆開銷"
        "edit_record" -> "修改記帳內容"
        "expense_amount" -> "消費金額 ($)"
        "select_date" -> "日期"
        "change_date" -> "換個日期"
        "select_category" -> "這是什麼樣的消費呢？"
        "note_optional" -> "寫點小備註吧 (選填)"
        "laundry_chip" -> "洗衣 ($20)"
        "dryer_chip" -> "烘衣 ($20)"
        "monthly_overview" -> "本月金庫進度"
        "monthly_status" -> "本月金庫概況"
        "daily_status" -> "今日額度概況"
        "spent" -> "已花費"
        "month_spent" -> "本月已花費"
        "today_spent" -> "今天已花費"
        "remaining" -> "金庫還剩"
        "month_remaining" -> "本月剩餘金庫"
        "today_remaining" -> "今天還能花"
        "over_budget" -> "稍微超支囉"
        "month_over" -> "本月超支"
        "today_over" -> "今天超支"
        "near_limit" -> "快花到上限囉"
        "today_ample" -> "今天額度很充裕"
        "month_progress" -> "金庫用量"
        "total_budget" -> "月預算目標"
        "avg_daily_budget" -> "每日平均額度"
        "dynamic_daily_budget" -> "動態靈活配額"
        "records_breakdown" -> "記帳細項紀錄"
        "subtotal" -> "當天小計"
        "no_records" -> "今天還沒記帳呢！要來紀錄第一筆小開銷嗎？"
        "add_first" -> "開始第一筆記帳"
        "pie_chart" -> "圓餅圖分佈"
        "daily_chart" -> "每日消費趨勢"
        "budget_usage" -> "金庫已使用"
        "total_expense" -> "總花費"
        "unused_budget" -> "尚未花費"
        "daily_avg" -> "平均每日"
        "daily_max" -> "單日最高"
        "day_unit" -> "日"
        "save" -> "儲存紀錄"
        "update_record" -> "儲存修改"
        "cancel" -> "取消"
        "close" -> "關閉"
        "confirm" -> "確定"
        "delete_item" -> "刪除這筆紀錄"
        "edit_item" -> "修改這筆紀錄"
        "select_report_month" -> "查看歷史月份"
        "month_report_hint" -> "點擊月份即可回顧該月份的支出細項與財務圖表分析。"
        "report_summary" -> "歷史報表概覽"
        "return_current_month" -> "回到這個月"
        "viewing_history" -> "正在回顧歷史資料"
        "welcome_title" -> "歡迎來到 Budget Manager"
        "welcome_subtitle" -> "輕鬆幾步設定，展開您的專屬智慧理財"
        "start_app" -> "開始理財"
        "invalid_budget_hint" -> "哎呀！金額好像忘記填或填錯囉"
        "daily_breakdown_title" -> "每日詳細花費明細"
        "active_days" -> "記帳天數"
        "days_unit" -> "天"
        "click_to_view_detail" -> "點擊檢視詳細花費明細 ›"
        else -> key
    }

    private fun getEn(key: String): String = when (key) {
        "vault_overview" -> "Vault Overview"
        "spent_this_month" -> "Spent This Month"
        "remaining_vault" -> "Remaining Vault"
        "vault_usage" -> "Vault Usage"
        "target_budget" -> "Target Budget"
        "daily_subtotal" -> "Daily Subtotal"
        "no_records_title" -> "No Records Today"
        "no_records_subtitle" -> "Log your first expense today!"
        "start_add" -> "Log First Record"
        "step_language" -> "Select Display Language"
        "step_theme" -> "Select Theme Color"
        "step_budget" -> "Set Monthly Budget"
        "settings" -> "Settings & Tools"
        "set_budget" -> "Plan Monthly Budget"
        "monthly_budget" -> "Total Monthly Target ($)"
        "theme_color" -> "Theme Color"
        "app_language" -> "Language"
        "add_record" -> "Add Record"
        "add_expense" -> "Add Expense"
        "edit_record" -> "Edit Record"
        "expense_amount" -> "Expense Amount ($)"
        "select_date" -> "Date"
        "change_date" -> "Change Date"
        "select_category" -> "Category"
        "note_optional" -> "Note (Optional)"
        "laundry_chip" -> "Laundry ($20)"
        "dryer_chip" -> "Dryer ($20)"
        "monthly_overview" -> "Monthly Progress"
        "monthly_status" -> "Monthly Budget Status"
        "daily_status" -> "Today's Budget Status"
        "spent" -> "Spent"
        "month_spent" -> "Month Spent"
        "today_spent" -> "Today Spent"
        "remaining" -> "Remaining"
        "month_remaining" -> "Month Remaining"
        "today_remaining" -> "Today Remaining"
        "over_budget" -> "Over Budget"
        "month_over" -> "Month Over"
        "today_over" -> "Today Over"
        "near_limit" -> "Near Limit"
        "today_ample" -> "On Track"
        "month_progress" -> "Month Progress"
        "total_budget" -> "Total Budget"
        "avg_daily_budget" -> "Daily Budget"
        "dynamic_daily_budget" -> "Flex Allowance"
        "records_breakdown" -> "Itemized Records"
        "subtotal" -> "Subtotal"
        "no_records" -> "No records today! Add your first record."
        "add_first" -> "Add First Record"
        "pie_chart" -> "Category Pie Chart"
        "daily_chart" -> "Daily Usage Chart"
        "budget_usage" -> "Budget Usage"
        "total_expense" -> "Total Expense"
        "unused_budget" -> "Unused Budget"
        "daily_avg" -> "Daily Avg"
        "daily_max" -> "Daily Max"
        "day_unit" -> "Day "
        "save" -> "Save"
        "update_record" -> "Update Record"
        "cancel" -> "Cancel"
        "close" -> "Close"
        "confirm" -> "OK"
        "delete_item" -> "Delete Record"
        "edit_item" -> "Edit Record"
        "select_report_month" -> "Select Monthly Report"
        "month_report_hint" -> "Select a month to view detailed expenses, budget, and charts."
        "report_summary" -> "Report Overview"
        "return_current_month" -> "Return to Current Month"
        "viewing_history" -> "Viewing Historical Report"
        "welcome_title" -> "Welcome to Budget Manager"
        "welcome_subtitle" -> "Set up in a few simple steps to start smart budgeting"
        "start_app" -> "Get Started"
        "invalid_budget_hint" -> "Please enter a valid budget amount"
        "daily_breakdown_title" -> "Daily Breakdown"
        "active_days" -> "Active Days"
        "days_unit" -> "Days"
        "click_to_view_detail" -> "Tap for Daily Breakdown ›"
        else -> key
    }
}
