package com.example.debit.ui.utils

import com.example.debit.data.AppLanguage

object AppStrings {
    fun getCategoryName(category: String, language: AppLanguage): String {
        if (language == AppLanguage.ZH) return category
        return when (category) {
            "餐飲" -> "Dining"
            "日常" -> "Daily"
            "娛樂" -> "Entertainment"
            "購物" -> "Shopping"
            "交通" -> "Transport"
            "醫療" -> "Medical"
            "居住" -> "Housing"
            "其他" -> "Other"
            else -> category
        }
    }

    fun getSubCategoryName(sub: String, language: AppLanguage): String {
        if (language == AppLanguage.ZH) return sub
        return when (sub) {
            "早餐" -> "Breakfast"
            "午餐" -> "Lunch"
            "晚餐" -> "Dinner"
            "宵夜" -> "Late Snack"
            "點心飲料" -> "Snacks & Drinks"
            "洗衣" -> "Laundry"
            "烘衣" -> "Dryer"
            "電費" -> "Electricity"
            "日用品" -> "Household"
            else -> sub
        }
    }

    fun get(key: String, language: AppLanguage): String {
        return if (language == AppLanguage.ZH) getZhTw(key) else getEn(key)
    }

    private fun getZhTw(key: String): String = when (key) {
        "settings" -> "偏好設定與工具"
        "set_budget" -> "規劃月度小金庫"
        "monthly_budget" -> "本月目標金庫 ($)"
        "theme_color" -> "色彩主題"
        "app_language" -> "語言偏好"
        "add_record" -> "記一筆"
        "add_expense" -> "新增一筆開銷"
        "edit_record" -> "修改記帳內容"
        "expense_amount" -> "消費金額 ($)"
        "select_date" -> "日期"
        "change_date" -> "換個日期"
        "select_category" -> "這是什麼樣的消費呢？"
        "note_optional" -> "寫點小備註吧 (選填)"
        "laundry_chip" -> "洗衣 ($20)"
        "dryer_chip" -> "烘衣 ($20)"
        "monthly_overview" -> "本月金庫進度"
        "monthly_status" -> "本月金庫概況"
        "daily_status" -> "今日額度概況"
        "spent" -> "已花費"
        "month_spent" -> "本月已花費"
        "today_spent" -> "今天已花費"
        "remaining" -> "金庫還剩"
        "month_remaining" -> "本月剩餘金庫"
        "today_remaining" -> "今天還能花"
        "over_budget" -> "稍微超支囉"
        "month_over" -> "本月超支"
        "today_over" -> "今天超支"
        "near_limit" -> "快花到上限囉"
        "today_ample" -> "今天額度很充裕"
        "month_progress" -> "金庫用量"
        "total_budget" -> "月預算目標"
        "avg_daily_budget" -> "每日平均額度"
        "dynamic_daily_budget" -> "動態靈活配額"
        "records_breakdown" -> "記帳細項紀錄"
        "subtotal" -> "當天小計"
        "no_records" -> "今天還沒記帳呢！要來紀錄第一筆小開銷嗎？"
        "add_first" -> "開始第一筆記帳"
        "pie_chart" -> "圓餅圖分佈"
        "daily_chart" -> "每日消費趨勢"
        "budget_usage" -> "金庫已使用"
        "total_expense" -> "總花費"
        "unused_budget" -> "尚未花費"
        "daily_avg" -> "平均每日"
        "daily_max" -> "單日最高"
        "day_unit" -> "日"
        "save" -> "儲存紀錄"
        "update_record" -> "儲存修改"
        "cancel" -> "取消"
        "close" -> "關閉"
        "confirm" -> "確定"
        "delete_item" -> "刪除這筆紀錄"
        "edit_item" -> "修改這筆紀錄"
        "select_report_month" -> "查看歷史月份"
        "month_report_hint" -> "點擊月份即可回顧該月份的支出細項與財務圖表分析。"
        "report_summary" -> "歷史報表概覽"
        "return_current_month" -> "回到這個月"
        "viewing_history" -> "正在回顧歷史資料"
        "welcome_title" -> "歡迎來到 Budget Manager"
        "welcome_subtitle" -> "輕鬆幾步設定，展開您的專屬智慧理財"
        "start_app" -> "開始理財"
        "invalid_budget_hint" -> "哎呀！金額好像忘記填或填錯囉"
        "daily_breakdown_title" -> "每日詳細花費明細"
        "active_days" -> "記帳天數"
        "days_unit" -> "天"
        "click_to_view_detail" -> "點擊檢視詳細花費明細 ›"
        else -> key
    }

    private fun getZhCn(key: String): String = when (key) {
        "settings" -> "偏好设置与工具"
        "set_budget" -> "规划月度小金库"
        "monthly_budget" -> "本月目标金库 ($)"
        "theme_color" -> "色彩主题"
        "app_language" -> "语言偏好"
        "add_record" -> "记一笔"
        "add_expense" -> "新增一笔开销"
        "edit_record" -> "修改记账内容"
        "expense_amount" -> "消费金额 ($)"
        "select_date" -> "日期"
        "change_date" -> "换个日期"
        "select_category" -> "这是什么样的消费呢？"
        "note_optional" -> "写点小备注吧 (选填)"
        "laundry_chip" -> "洗衣 ($20)"
        "dryer_chip" -> "烘干 ($20)"
        "monthly_overview" -> "本月金库进度"
        "monthly_status" -> "本月金库概况"
        "daily_status" -> "今日额度概况"
        "spent" -> "已花费"
        "month_spent" -> "本月已花费"
        "today_spent" -> "今天已花费"
        "remaining" -> "金库还剩"
        "month_remaining" -> "本月剩余金库"
        "today_remaining" -> "今天还能花"
        "over_budget" -> "稍微超支啰"
        "month_over" -> "本月超支"
        "today_over" -> "今天超支"
        "near_limit" -> "快花到上限啰"
        "today_ample" -> "今天额度很充裕"
        "month_progress" -> "金库用量"
        "total_budget" -> "月预算目标"
        "avg_daily_budget" -> "每日平均额度"
        "dynamic_daily_budget" -> "动态灵活配额"
        "records_breakdown" -> "记账细项纪录"
        "subtotal" -> "当天小计"
        "no_records" -> "今天还没记账呢！要来纪录第一笔小开销吗？"
        "add_first" -> "开始第一笔记账"
        "pie_chart" -> "饼图分布"
        "daily_chart" -> "每日消费趋势"
        "budget_usage" -> "金库已使用"
        "total_expense" -> "总花费"
        "unused_budget" -> "尚未花费"
        "daily_avg" -> "平均每日"
        "daily_max" -> "单日最高"
        "day_unit" -> "日"
        "save" -> "保存纪录"
        "update_record" -> "保存修改"
        "cancel" -> "取消"
        "close" -> "关闭"
        "confirm" -> "确定"
        "delete_item" -> "删除这笔纪录"
        "edit_item" -> "修改这笔纪录"
        "select_report_month" -> "查看历史月份"
        "month_report_hint" -> "点击月份即可回顾该月份的支出细项与财务图表分析。"
        "report_summary" -> "历史报表概览"
        "return_current_month" -> "回到这个月"
        "viewing_history" -> "正在回顾历史数据"
        "welcome_title" -> "欢迎来到 Budget Manager"
        "welcome_subtitle" -> "轻松几步设置，展开您的专属智慧理财"
        "start_app" -> "开始理财"
        "invalid_budget_hint" -> "哎呀！金额好像忘记填或填错啰"
        "daily_breakdown_title" -> "每日详细花费明细"
        "active_days" -> "记账天数"
        "days_unit" -> "天"
        "click_to_view_detail" -> "点击查看详细花费明细 ›"
        else -> key
    }

    private fun getJa(key: String): String = when (key) {
        "settings" -> "設定とツール"
        "set_budget" -> "月間予算を設定"
        "monthly_budget" -> "今月の予算目標 ($)"
        "theme_color" -> "テーマカラー"
        "app_language" -> "言語"
        "add_record" -> "記帳する"
        "add_expense" -> "支出を追加"
        "edit_record" -> "記録を編集"
        "expense_amount" -> "金額 ($)"
        "select_date" -> "日付"
        "change_date" -> "日付を変更"
        "select_category" -> "カテゴリを選択"
        "note_optional" -> "メモ (任意)"
        "laundry_chip" -> "洗濯 ($20)"
        "dryer_chip" -> "乾燥 ($20)"
        "monthly_overview" -> "今月の進捗"
        "monthly_status" -> "月間予算状況"
        "daily_status" -> "今日の予算状況"
        "spent" -> "支出額"
        "month_spent" -> "今月の支出"
        "today_spent" -> "今日の支出"
        "remaining" -> "残額"
        "month_remaining" -> "今月の残額"
        "today_remaining" -> "今日の利用可能額"
        "over_budget" -> "予算オーバー"
        "month_over" -> "今月の超過額"
        "today_over" -> "今日の超過額"
        "near_limit" -> "上限に接近"
        "today_ample" -> "予算順調"
        "month_progress" -> "予算消化率"
        "total_budget" -> "月間予算"
        "avg_daily_budget" -> "日別平均予算"
        "dynamic_daily_budget" -> "調整可能額"
        "records_breakdown" -> "支出履歴"
        "subtotal" -> "小計"
        "no_records" -> "今日の記録はまだありません。最初の支出を追加してみましょう！"
        "add_first" -> "最初の記録を追加"
        "pie_chart" -> "カテゴリ円グラフ"
        "daily_chart" -> "日別支出トレンド"
        "budget_usage" -> "予算消化"
        "total_expense" -> "総支出"
        "unused_budget" -> "予算残額"
        "daily_avg" -> "日別平均"
        "daily_max" -> "日別最高"
        "day_unit" -> "日"
        "save" -> "保存"
        "update_record" -> "更新"
        "cancel" -> "キャンセル"
        "close" -> "閉じる"
        "confirm" -> "OK"
        "delete_item" -> "削除"
        "edit_item" -> "編集"
        "select_report_month" -> "履歴月を選択"
        "month_report_hint" -> "月を選択して詳細な支出分析とグラフを確認します。"
        "report_summary" -> "レポート概要"
        "return_current_month" -> "今月へ戻る"
        "viewing_history" -> "過去データを確認中"
        "welcome_title" -> "Budget Manager へようこそ"
        "welcome_subtitle" -> "簡単な設定でスマートな家計管理を始めましょう"
        "start_app" -> "はじめる"
        "invalid_budget_hint" -> "有効な金額を入力してください"
        "daily_breakdown_title" -> "日別詳細"
        "active_days" -> "記録日数"
        "days_unit" -> "日"
        "click_to_view_detail" -> "詳細を表示 ›"
        else -> key
    }

    private fun getKo(key: String): String = when (key) {
        "settings" -> "설정 및 도구"
        "set_budget" -> "월예산 설정"
        "monthly_budget" -> "이번 달 예산 목표 ($)"
        "theme_color" -> "테마 색상"
        "app_language" -> "언어 설정"
        "add_record" -> "지출 기록"
        "add_expense" -> "지출 추가"
        "edit_record" -> "기록 수정"
        "expense_amount" -> "지출 금액 ($)"
        "select_date" -> "날짜"
        "change_date" -> "날짜 변경"
        "select_category" -> "카테고리 선택"
        "note_optional" -> "메모 (선택사항)"
        "laundry_chip" -> "세탁 ($20)"
        "dryer_chip" -> "건조 ($20)"
        "monthly_overview" -> "이번 달 예산 현황"
        "monthly_status" -> "월예산 요약"
        "daily_status" -> "오늘의 예산 현황"
        "spent" -> "지출액"
        "month_spent" -> "이번 달 지출"
        "today_spent" -> "오늘 지출"
        "remaining" -> "잔액"
        "month_remaining" -> "이번 달 잔액"
        "today_remaining" -> "오늘 사용 가능액"
        "over_budget" -> "예산 초과"
        "month_over" -> "월 예산 초과"
        "today_over" -> "오늘 예산 초과"
        "near_limit" -> "예산 한도 임박"
        "today_ample" -> "예산 여유"
        "month_progress" -> "예산 사용률"
        "total_budget" -> "총 월예산"
        "avg_daily_budget" -> "일평균 예산"
        "dynamic_daily_budget" -> "유동 예산"
        "records_breakdown" -> "지출 내역"
        "subtotal" -> "소계"
        "no_records" -> "오늘 내역이 없습니다. 첫 지출을 기록해보세요!"
        "add_first" -> "첫 지출 기록하기"
        "pie_chart" -> "카테고리 파이 차트"
        "daily_chart" -> "일별 지출 추이"
        "budget_usage" -> "예산 사용"
        "total_expense" -> "총지출"
        "unused_budget" -> "남은 예산"
        "daily_avg" -> "일평균"
        "daily_max" -> "일일 최고"
        "day_unit" -> "일"
        "save" -> "저장"
        "update_record" -> "수정 완료"
        "cancel" -> "취소"
        "close" -> "닫기"
        "confirm" -> "확인"
        "delete_item" -> "삭제"
        "edit_item" -> "수정"
        "select_report_month" -> "조회 월 선택"
        "month_report_hint" -> "월을 선택하여 상세 지출 분석과 차트를 확인하세요."
        "report_summary" -> "월별 리포트 개요"
        "return_current_month" -> "이번 달로 이동"
        "viewing_history" -> "지난 내역 조회 중"
        "welcome_title" -> "Budget Manager에 오신 것을 환영합니다"
        "welcome_subtitle" -> "간단한 설정으로 스마트한 가계 관리를 시작하세요"
        "start_app" -> "시작하기"
        "invalid_budget_hint" -> "올바른 금액을 입력해주세요"
        "daily_breakdown_title" -> "일별 상세 내역"
        "active_days" -> "기록 일수"
        "days_unit" -> "일"
        "click_to_view_detail" -> "상세 보기 ›"
        else -> key
    }

    private fun getEs(key: String): String = when (key) {
        "settings" -> "Ajustes y Herramientas"
        "set_budget" -> "Configurar Presupuesto Mensual"
        "monthly_budget" -> "Presupuesto Mensual ($)"
        "theme_color" -> "Color de Tema"
        "app_language" -> "Idioma"
        "add_record" -> "Añadir Registro"
        "add_expense" -> "Nuevo Gasto"
        "edit_record" -> "Editar Registro"
        "expense_amount" -> "Monto del Gasto ($)"
        "select_date" -> "Fecha"
        "change_date" -> "Cambiar Fecha"
        "select_category" -> "Seleccionar Categoría"
        "note_optional" -> "Nota (Opcional)"
        "laundry_chip" -> "Lavandería ($20)"
        "dryer_chip" -> "Secadora ($20)"
        "monthly_overview" -> "Progreso Mensual"
        "monthly_status" -> "Estado del Presupuesto Mensual"
        "daily_status" -> "Estado Diario"
        "spent" -> "Gastado"
        "month_spent" -> "Gastado este mes"
        "today_spent" -> "Gastado hoy"
        "remaining" -> "Restante"
        "month_remaining" -> "Restante del mes"
        "today_remaining" -> "Disponible hoy"
        "over_budget" -> "Presupuesto Excedido"
        "month_over" -> "Exceso mensual"
        "today_over" -> "Exceso diario"
        "near_limit" -> "Cerca del límite"
        "today_ample" -> "En orden"
        "month_progress" -> "Uso del Presupuesto"
        "total_budget" -> "Presupuesto Total"
        "avg_daily_budget" -> "Presupuesto Diario Promedio"
        "dynamic_daily_budget" -> "Margen Flexible"
        "records_breakdown" -> "Historial de Gastos"
        "subtotal" -> "Subtotal"
        "no_records" -> "¡No hay registros hoy! Añade tu primer gasto."
        "add_first" -> "Añadir Primer Registro"
        "pie_chart" -> "Gráfico por Categorías"
        "daily_chart" -> "Tendencia Diaria"
        "budget_usage" -> "Uso del Presupuesto"
        "total_expense" -> "Gasto Total"
        "unused_budget" -> "Presupuesto No Usado"
        "daily_avg" -> "Promedio Diario"
        "daily_max" -> "Máximo Diario"
        "day_unit" -> "Día"
        "save" -> "Guardar"
        "update_record" -> "Actualizar"
        "cancel" -> "Cancelar"
        "close" -> "Cerrar"
        "confirm" -> "Aceptar"
        "delete_item" -> "Eliminar"
        "edit_item" -> "Editar"
        "select_report_month" -> "Seleccionar Mes"
        "month_report_hint" -> "Selecciona un mes para ver análisis detallados y gráficos."
        "report_summary" -> "Resumen del Reporte"
        "return_current_month" -> "Volver al Mes Actual"
        "viewing_history" -> "Viendo Historial"
        "welcome_title" -> "Bienvenido a Budget Manager"
        "welcome_subtitle" -> "Configura en pocos pasos para gestionar tu dinero inteligentemente"
        "start_app" -> "Comenzar"
        "invalid_budget_hint" -> "Por favor ingresa un monto válido"
        "daily_breakdown_title" -> "Desglose Diario"
        "active_days" -> "Días Registrados"
        "days_unit" -> "días"
        "click_to_view_detail" -> "Toca para ver desglose ›"
        else -> key
    }

    private fun getEn(key: String): String = when (key) {
        "settings" -> "Settings & Tools"
        "set_budget" -> "Plan Monthly Budget"
        "monthly_budget" -> "Total Monthly Target ($)"
        "theme_color" -> "Theme Color"
        "app_language" -> "Language"
        "add_record" -> "Add Record"
        "add_expense" -> "Add Expense"
        "edit_record" -> "Edit Record"
        "expense_amount" -> "Expense Amount ($)"
        "select_date" -> "Date"
        "change_date" -> "Change Date"
        "select_category" -> "Category"
        "note_optional" -> "Note (Optional)"
        "laundry_chip" -> "Laundry ($20)"
        "dryer_chip" -> "Dryer ($20)"
        "monthly_overview" -> "Monthly Progress"
        "monthly_status" -> "Monthly Budget Status"
        "daily_status" -> "Today's Budget Status"
        "spent" -> "Spent"
        "month_spent" -> "Month Spent"
        "today_spent" -> "Today Spent"
        "remaining" -> "Remaining"
        "month_remaining" -> "Month Remaining"
        "today_remaining" -> "Today Remaining"
        "over_budget" -> "Over Budget"
        "month_over" -> "Month Over"
        "today_over" -> "Today Over"
        "near_limit" -> "Near Limit"
        "today_ample" -> "On Track"
        "month_progress" -> "Month Progress"
        "total_budget" -> "Total Budget"
        "avg_daily_budget" -> "Daily Budget"
        "dynamic_daily_budget" -> "Flex Allowance"
        "records_breakdown" -> "Itemized Records"
        "subtotal" -> "Subtotal"
        "no_records" -> "No records today! Add your first record."
        "add_first" -> "Add First Record"
        "pie_chart" -> "Category Pie Chart"
        "daily_chart" -> "Daily Usage Chart"
        "budget_usage" -> "Budget Usage"
        "total_expense" -> "Total Expense"
        "unused_budget" -> "Unused Budget"
        "daily_avg" -> "Daily Avg"
        "daily_max" -> "Daily Max"
        "day_unit" -> "Day "
        "save" -> "Save"
        "update_record" -> "Update Record"
        "cancel" -> "Cancel"
        "close" -> "Close"
        "confirm" -> "OK"
        "delete_item" -> "Delete Record"
        "edit_item" -> "Edit Record"
        "select_report_month" -> "Select Monthly Report"
        "month_report_hint" -> "Select a month to view detailed expenses, budget, and charts."
        "report_summary" -> "Report Overview"
        "return_current_month" -> "Return to Current Month"
        "viewing_history" -> "Viewing Historical Report"
        "welcome_title" -> "Welcome to Budget Manager"
        "welcome_subtitle" -> "Set up in a few simple steps to start smart budgeting"
        "start_app" -> "Get Started"
        "invalid_budget_hint" -> "Please enter a valid budget amount"
        "daily_breakdown_title" -> "Daily Breakdown"
        "active_days" -> "Active Days"
        "days_unit" -> "Days"
        "click_to_view_detail" -> "Tap for Daily Breakdown ›"
        else -> key
    }
}
